import {
  ConflictException,
  Injectable,
  Logger,
  NotFoundException,
  OnApplicationBootstrap,
  UnauthorizedException,
} from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import { InjectRepository } from '@nestjs/typeorm';
import * as bcrypt from 'bcrypt';
import type { FastifyReply } from 'fastify';
import { Repository } from 'typeorm';

import { config } from '../config.js';
import { User } from '../users/user.entity.js';
import type { LoginDto } from './login.dto.js';
import type { RegisterDto } from './register.dto.js';
import type { UpdateProfileDto } from './update-profile.dto.js';

const BCRYPT_COST = 12;

@Injectable()
export class AuthService implements OnApplicationBootstrap {
  private readonly logger = new Logger(AuthService.name);
  constructor(
    @InjectRepository(User) private readonly users: Repository<User>,
    private readonly jwtService: JwtService
  ) {}

  async onApplicationBootstrap() {
    const count = await this.users.count();
    if (count > 0) return;

    const email = config.ADMIN_EMAIL.toLowerCase();
    // ADMIN_PASSWORD is already a bcrypt hash (generated by `pnpm setup`).
    // We store it directly — no re-hashing needed.
    const passwordHash = config.ADMIN_PASSWORD;
    if (!passwordHash.startsWith('$2')) {
      // Fallback: if someone set a plaintext password, hash it.
      this.logger.warn(
        'ADMIN_PASSWORD does not look like a bcrypt hash — hashing it now. Run `pnpm setup` for a pre-hashed password.'
      );
      const fallbackHash = await bcrypt.hash(passwordHash, BCRYPT_COST);
      await this.users.save(
        this.users.create({
          email,
          passwordHash: fallbackHash,
          displayName: 'Admin',
          avatarUrl: null,
          role: 'admin',
        })
      );
      return;
    }
    await this.users.save(
      this.users.create({
        email,
        passwordHash,
        displayName: 'Admin',
        avatarUrl: null,
        role: 'admin',
      })
    );
  }

  private signToken(user: User) {
    return this.jwtService.sign({
      sub: user.id,
      email: user.email,
      role: user.role,
      displayName: user.displayName,
      avatarUrl: this.resolveAvatarUrl(user.avatarUrl),
    });
  }

  /**
   * Sign an access token for the given user. Exposed so the OAuth
   * module can issue tokens without duplicating the JWT configuration.
   */
  async signAccessToken(userId: string): Promise<string> {
    const user = await this.users.findOne({ where: { id: userId } });
    if (!user) {
      throw new NotFoundException('User not found');
    }
    return this.signToken(user);
  }

  private toPublic(user: User) {
    return {
      id: user.id,
      email: user.email,
      displayName: user.displayName,
      avatarUrl: this.resolveAvatarUrl(user.avatarUrl),
      role: user.role,
    };
  }

  /**
   * Convert relative /uploads/ paths to absolute URLs so avatars work
   * on other services (rsnra-link, resomd) that receive this URL via
   * OAuth/userinfo. Absolute URLs (http/https) are passed through.
   */
  private resolveAvatarUrl(url: string | null): string | null {
    if (!url) return null;
    if (url.startsWith('http://') || url.startsWith('https://')) return url;
    const base = config.AUTH_API_PUBLIC_URL.replace(/\/$/, '');
    return `${base}${url}`;
  }

  attachSessionCookie(reply: FastifyReply, accessToken: string) {
    const isProduction = config.NODE_ENV === 'production';
    const domain =
      config.COOKIE_DOMAIN ?? (isProduction ? '.rsnra.com' : undefined);
    const attributes = [
      `rsnra_session=${accessToken}`,
      'Path=/',
      'HttpOnly',
      'SameSite=Lax',
      'Max-Age=31536000',
      domain ? `Domain=${domain}` : null,
      isProduction ? 'Secure' : null,
    ].filter(Boolean);
    reply.header('Set-Cookie', attributes.join('; '));
  }

  clearSessionCookie(reply: FastifyReply) {
    const isProduction = config.NODE_ENV === 'production';
    const domain =
      config.COOKIE_DOMAIN ?? (isProduction ? '.rsnra.com' : undefined);
    const attributes = [
      'rsnra_session=',
      'Path=/',
      'HttpOnly',
      'SameSite=Lax',
      'Max-Age=0',
      domain ? `Domain=${domain}` : null,
      isProduction ? 'Secure' : null,
    ].filter(Boolean);
    reply.header('Set-Cookie', attributes.join('; '));
  }

  async register(dto: RegisterDto) {
    const existing = await this.users.findOne({
      where: { email: dto.email.toLowerCase() },
    });
    if (existing) {
      throw new ConflictException('Email is already registered');
    }

    const passwordHash = await bcrypt.hash(dto.password, BCRYPT_COST);
    const user = this.users.create({
      email: dto.email.toLowerCase(),
      passwordHash,
      displayName: dto.displayName ?? null,
      avatarUrl: null,
      role: 'user',
    });
    await this.users.save(user);

    return { accessToken: this.signToken(user), user: this.toPublic(user) };
  }

  async login(dto: LoginDto) {
    const user = await this.users.findOne({
      where: { email: dto.email.toLowerCase() },
    });
    if (!user || !(await bcrypt.compare(dto.password, user.passwordHash))) {
      throw new UnauthorizedException('Invalid email or password');
    }

    return { accessToken: this.signToken(user), user: this.toPublic(user) };
  }

  async me(userId: string) {
    const user = await this.users.findOne({ where: { id: userId } });
    if (!user) {
      throw new NotFoundException('User not found');
    }
    return this.toPublic(user);
  }

  async updateProfile(userId: string, dto: UpdateProfileDto) {
    const user = await this.users.findOne({ where: { id: userId } });
    if (!user) {
      throw new NotFoundException('User not found');
    }
    if (dto.displayName !== undefined) user.displayName = dto.displayName;
    if (dto.avatarUrl !== undefined) user.avatarUrl = dto.avatarUrl;
    await this.users.save(user);
    return this.toPublic(user);
  }

  async deleteAccount(userId: string) {
    await this.users.delete({ id: userId });
  }

  async listUsers() {
    const users = await this.users.find({ order: { createdAt: 'DESC' } });
    return users.map(user => ({
      ...this.toPublic(user),
      createdAt: user.createdAt,
      updatedAt: user.updatedAt,
    }));
  }

  async updateUser(
    userId: string,
    dto: { displayName?: string; role?: User['role'] }
  ) {
    const user = await this.users.findOne({ where: { id: userId } });
    if (!user) {
      throw new NotFoundException('User not found');
    }
    if (dto.displayName !== undefined) user.displayName = dto.displayName;
    if (dto.role !== undefined) user.role = dto.role;
    await this.users.save(user);
    return {
      ...this.toPublic(user),
      createdAt: user.createdAt,
      updatedAt: user.updatedAt,
    };
  }
}
